#goal definition
int32 index
---
#result definition
bool action
int32 inductIndex
int32 destIndex 
---
#feedback
string axis
int32 point
string nextAxis
int32 nextPoint
int32 Xpoint
int32 Ypoint
float64 xVel
float64 yVel
